vcluster:
  enableHA: false
  coredns:
    replicas: 2
  plugin:
    hooks:
      image: harbor.fluidhq.io/public/vcluster-plugin@sha256:540eefa4608228e2f62159e04de23db8788cd21a20eb0fd4000ee0af26358d2e
      imagePullPolicy: IfNotPresent
  vcluster:
    image: rancher/k3s:v1.24.8-k3s1
    env:
      - name: K3S_DATASTORE_ENDPOINT
        value: postgres://root@cockroachdb-public:26257/defaultdb?serial_normalization=sql_sequence
      - name: K3S_DATASTORE_CERTFILE
        value: "/cockroach/cockroach-certs/client.root.crt"
      - name: K3S_DATASTORE_KEYFILE
        value: "/cockroach/cockroach-certs/client.root.key"
      - name: K3S_DATASTORE_CAFILE
        value: "/cockroach/cockroach-certs/ca.crt"
    volumeMounts:
      - mountPath: /data
        name: data
      - mountPath: /cockroach/cockroach-certs/
        name: datastore-tls
  volumes:
    - name: datastore-tls
      projected:
        defaultMode: 0600
        sources:
          - secret:
              items:
                - key: ca.crt
                  path: ca.crt
              name: cockroachdb-node
          - secret:
              items:
                - key: tls.crt
                  path: client.root.crt
                - key: tls.key
                  path: client.root.key
              name: cockroachdb-root
  storage:
    size: 10Gi
  syncer:
    extraArgs
      - --tls-san=*.kube.cloud.fluidhq.io
  sync:
    nodes:
      enabled: true
      enableScheduler: true
      syncAllNodes: true
