enableCrDb: false
vcluster:
  enableHA: false
  coredns:
    replicas: 2
  plugin:
    hooks:
      image: harborv2.fluidhq.io/public/vcluster-plugin:latest
      imagePullPolicy: IfNotPresent
  vcluster:
    image: rancher/k3s:v1.28.6-k3s2
    env:
      - name: K3S_DATASTORE_ENDPOINT
        value: ""
      - name: K3S_DATASTORE_CERTFILE
        value: ""
      - name: K3S_DATASTORE_KEYFILE
        value: ""
      - name: K3S_DATASTORE_CAFILE
        value: ""
  volumes: []
  telemetry:
    disabled: "true"
  storage:
    size: 10Gi
  syncer:
    extraArgs:
      - --tls-san=*.kube.cloud-dev.fluidhq.io
  sync:
    nodes:
      enabled: true
      enableScheduler: true
      syncAllNodes: true
